### ISSUE TITLE
Initial App Store submission checklist

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#206]
https://developer.apple.com/app-store/review/guidelines/#before-you-submit

## Approvals

- [x] Engineering (all required / P1 items complete)
- [x] Product Integrity (blocking bugs fixed)
  - Security - Requires #51
- Product Management
  - [x] Lockbox PM (ready for submission)
- Legal - Requires #203 
   - Privacy Policy: requires https://github.com/mozilla-lockbox/mozilla-lockbox.github.io/issues/57

## Other Preparation

- [x] update FxA client ID
- [x] test sign in account for Apple Testers (`dreams+appletest@mozilla.com`)
- ~well-known file stored on website and accessible to iOS app~

## Apple App Store

- Test Flight page/assets - Requires #125
- App Store assets - Requires #176 and Requires #177

**Comment by devinreams** [comment]
>well-known file stored on website and accessible to iOS app

@sashei @linuxwolf I added this to my launch checklist and wanted to check with you: is anything actually still applicable?

I know we created and tested hosting `well-known` files for FxA back here: https://github.com/mozilla-lockbox/mozilla-lockbox.github.io/pull/17

But I don't think there's anything else we're needing "to do", is that right?

**Comment by devinreams** [comment]
Engineering, Product, and PI are ["GO"](https://docs.google.com/spreadsheets/d/17yKyVZcpWq9Xszr4ZenUUQPRtbifLcINbWf9wYOLdBo/edit#gid=0) for store submission.

TestFlight build distributed to all internal and external testers ✅ 

Will wait overnight for any last-minute issues or concerns (non expected) and submit early Friday morning, Pacific time.

**Comment by devinreams** [comment]
![screen shot 2018-06-01 at 8 59 05 am](https://user-images.githubusercontent.com/49511/40847615-1c6d1dbc-657a-11e8-9cf9-b4f6aa4e312d.png)

...and now we wait.
