### ISSUE TITLE
Navigation bar action link updates

### ISSUE THREAD

**Issue by nickbrandt** [mozilla-lockbox/lockbox-ios#251]
In order to have consistency across the app, we want to update some of the press states for action links/icons within the navigation bar.

**Press state value: #ffffff @ 60% opacity (both text & icons)**

- [x] "Cancel" action link in FxA authentication screens + update text to "Close"
- [x] Settings icon on Entry List screen
- [x] Down caret icon (in sort) on Entry List screen
- [x] Back chevron icon on Entry Detail screen
- [x] "< Settings" action link (icon and text) on Account screen (see #337)
- [x] update padding between "<" & "Settings" (see #208)
- [x] Center the "Firefox Lockbox" text on small screen (iPhone SE #372)

Related to #223

**Comment by devinreams** [comment]
>"< Settings" action link (icon and text) on Account screen + update padding between "<" & "Settings"

See more at #251

**Comment by devinreams** [comment]
>"< Settings" action link (icon and text)

Also related issue in 10.3 in #337
