### ISSUE TITLE
Welcome & loading screen content updates

### ISSUE THREAD

**Issue by nickbrandt** [mozilla-lockbox/lockbox-ios#306]
Content updates to the welcome & loading screens based on content review.

## Tasks
**Welcome (first run) / Welcome (returning user) / Loading Screen**
- [x] Update slogan to: “Take your passwords everywhere”
- [x] Update "Lockbox" to: "Firefox Lockbox"

**Welcome (first run)**
- [x] Update copy to: "To use Firefox Lockbox, you’ll need a Firefox Account with saved logins."
- [x] “Learn more [chevron-right]” link opens FAQ to anchored section
Link directs to: https://lockbox.firefox.com/faq.html#how-do-i-use-lockbox

**Welcome (returning user)**
- [x] Update sign in with FxA button to: “Sign In”

## Visual Design
**InVision**
Loading Screen: https://mozilla.invisionapp.com/share/7JEUG47ZU#/267561207_Loading_Screen
Welcome: https://mozilla.invisionapp.com/share/BQEUSO0S2#/267560515_Welcome
Welcome (Returning User - Touch ID): https://mozilla.invisionapp.com/share/7JEUG47ZU#/288717368_Welcome_-_Returning_User_-_TouchID
Welcome (Returning User - Face ID): https://mozilla.invisionapp.com/share/7JEUG47ZU#/267560535_Welcome_-_Returning_User

**Zeplin**
Loading Screen: https://zpl.io/begYxoD
Welcome: https://zpl.io/aBjB70q
Welcome (Returning User - Touch ID) : https://zpl.io/V0ZW5xO
Welcome (Returning User - Face ID): https://zpl.io/aRNL9Ln
