### ISSUE TITLE
Access list of saved entries

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#45]
Upon signing into the Lockbox app, I want to be able to quickly access an app or website with my saved credentials.

Acceptance criteria:
* Should have immediate access to list of saved credentials

To start, this is a read-only access to those entries

- list view https://mozilla.invisionapp.com/share/7JEUG47ZU#/screens/267560598
  - title / username
  - kebab (does nothing)

no search bar or A-Z selector

## ToDo
- [ ] fleshed-out routing architecture
- [x] gradient for navbar

**Comment by sashei** [comment]
Todo still on this branch: 
- [ ] fleshed-out routing architecture
- [ ] gradient for navbar
