### ISSUE TITLE
Populating app or mobile web view with saved credentials via copy/paste

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#47]
When retrieving Lockbox entry details, I want to quickly copy my username and password to paste into the app.

# Acceptance criteria:
- copy and paste in 8 taps or less

# Tasks

https://mozilla.invisionapp.com/share/BGENZYVT4#/screens/266152008

- [ ] copy username from list kebab "..." 
- [ ] copy password from list kebab
- [ ] tap username field from detail view to copy
- [ ] tap password field from detail view to copy

**Comment by sashei** [comment]
I've broken this story down into its constituent engineering pieces (that would be issues #73, #74, #75, & #76). I'll close this story as the top-level epic & track ongoing work with the smaller stories.
