### ISSUE TITLE
Provide an iPad specific experience

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#745]
We continue to see user requests for a better iPad experience.

Right now 7% of our users are using the app on an iPad.

I'm opening this issue to explore the opportunities and define product requirements.

* [x] Architecture (Split View) #838
* [x] Launch screen #840 - https://app.zeplin.io/project/5a4e9ff8032d0923200a2635/screen/5c266e2d7501c0242a74cffb
* [x] Welcome Screen #840 - https://app.zeplin.io/project/5a4e9ff8032d0923200a2635/screen/5c1bd78375a3b4afa1294373
* [x] Settings #841 - https://app.zeplin.io/project/5a4e9ff8032d0923200a2635/screen/5c19385e75a3b4afa11ae404
* [x] Settings #849 #850 - 2nd level - https://app.zeplin.io/project/5a4e9ff8032d0923200a2635/screen/5c19385e2e3f282424aa66fc
* [x] Drag and Drop support #853 #854 
* [x] Onboarding Confirmation #851 - https://app.zeplin.io/project/5a4e9ff8032d0923200a2635/screen/5c266e4a839feeaf10712fa5
* [x] Webviews - https://app.zeplin.io/project/5a4e9ff8032d0923200a2635/screen/5c19385d12e8fd5096009163
* [x] Autofill UI - https://app.zeplin.io/project/5a4e9ff8032d0923200a2635/screen/5c19385e875176af8fed84a8
* [x] Empty State - https://app.zeplin.io/project/5a4e9ff8032d0923200a2635/screen/5c1aadaa0e0e0cb02dfc95b6
* [x] Autofill Onboarding #868 - https://app.zeplin.io/project/5a4e9ff8032d0923200a2635/screen/5c266e24b233e172481649ec
* [x] Lock Screen #869 - https://app.zeplin.io/project/5a4e9ff8032d0923200a2635/screen/5c1bd783a15cd3246e06806b
* [x] Autofill Setup - #868 https://app.zeplin.io/project/5a4e9ff8032d0923200a2635/screen/5c266eabb233e172481650e8
* [x] List selection state - highlight and blue #861 #862 #867 https://app.zeplin.io/project/5a4e9ff8032d0923200a2635/screen/5c19385e420c9e112aade6d7

**Comment by joeyg** [comment]
@nickbrandt - One of the items in this task is webviews. Do you mind checking to see if there is anything to do there?

**Comment by nickbrandt** [comment]
@joeyg those actually look good as is (filling entire screen), as in the designs provided. 👍 
https://zpl.io/aRWlvZz

**Comment by nickbrandt** [comment]
@devinreams I agree we should load this in a modal on iPad if we can. Initially I was thinking we were bound with handling this the same as iPhone, but it's ideal to treat this different with the space available on the iPad (maintaining context with what the user is doing)

. I've attached a couple screenshots of how I've seen competitors handle this, as well as a design for what would make sense for our app. I assume we would also be able to handle unlocking Lockbox within this modal as well (vs going to the full screen). I can mock that up if needed, just let me know.

It may be nice to have this focus on search when going to the credential list, since we are no longer doing filtering based on domain. Though we currently don't do that on iOS, so perhaps this should just be a new issue if we want to make that change. 

Interested in your thoughts as well @joeyg 

![screen shot 2019-01-23 at 10 03 34 am](https://user-images.githubusercontent.com/5185090/51623982-27808400-1ef7-11e9-912b-36eb9593133b.png)

![lockbox-autofill-ipad](https://user-images.githubusercontent.com/5185090/51624055-4f6fe780-1ef7-11e9-9be6-d2125d918f72.png)

**Comment by joeyg** [comment]
@nickbrandt It looks like the zeplin link for Autofill Onboarding is missing the new image or is that a video file? https://app.zeplin.io/project/5a4e9ff8032d0923200a2635/screen/5c266eabb233e172481650e8

**Comment by devinreams** [comment]
I took a quick look at the open PRs and closed items and updated the original "todo list" above.

I _believe_ everything originally designed and planned for iPad is now accounted for in the code or open pull requests. 🎉

**Comment by devinreams** [comment]
>I've attached a couple screenshots of how I've seen competitors handle this, as well as a design for what would make sense for our app. I assume we would also be able to handle unlocking Lockbox within this modal as well (vs going to the full screen).

@nickbrandt Regarding the “AutoFill” modal: I took a look at the current state and here’s what we have:

![img_0032](https://user-images.githubusercontent.com/49511/52224289-dbbdcb00-2864-11e9-839c-a080152f9d29.png)

Can you check that out and make sure we’ve got this piece “completed” to your satisfaction? If not please feel free to open new issues.

>It may be nice to have this focus on search when going to the credential list, since we are no longer doing filtering based on domain. Though we currently don't do that on iOS, so perhaps this should just be a new issue if we want to make that change.

OK, I’ll open that up right now as a potential improvement: 
https://github.com/mozilla-lockbox/lockbox-ios/issues/872

**Comment by nickbrandt** [comment]
@devinreams thanks for pointing this out, I've created a new issue (#873 ) that highlights just a couple small nits. @joeyg let me know if you have any questions.

**Comment by devinreams** [comment]
I'm closing this long-running issue as all the original requirements have been closed (and double checked).

We'll push an internal test release out via TestFlight, perform QA testing, and then triage/prioritize any release blocking bugs before we put this out to the public.  🚀
