### ISSUE TITLE
Use FxA UID & scoped key in datastore initialization

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#87]
# Prerequisites
- [x] CJOSE support for ECDH-ES (tracking [here](https://github.com/linuxwolf/cjose/tree/ecdh-es))

# Todo
- [x] (3rd party) implement ECDH-ES support
- [x] generate and publish ECDH keypair via /authorization request
- [x] obtain and decrypt key bundle from /token response
- [x] initialize Lockbox DataStore with UID and scoped key
