### ISSUE TITLE
Mobile alpha evaluative research for usability  understanding

### ISSUE THREAD

**Issue by hmcgaw** [mozilla-lockbox/lockbox-ios#96]
Run study to evaluate usability Lockbox beta on mobile

**Acceptance criteria**
Once the study is completed recommendations have been shared with team and broken into new cards for the backlog.

**Tasks**
- [ ] Research kickoff (questions, goals)
- [ ] Prepare research protocol
- [ ] Update designs/prototype to reflect needs of protocol
- [ ] Build study (if unmoderated) OR begin recruitment (if moderated)
- [ ] Observe sessions OR conduct study
- [ ] Analyze data
- [ ] Prepare findings for distribution

**Comment by hmcgaw** [comment]
Results: https://docs.google.com/spreadsheets/d/1ACTai3jKakRH2PrzbHHeIJGyAbVhuTAnIvk8iGEVgiE/edit#gid=12
